### ISSUE TITLE
build fails if you import keyframes directly

### ISSUE THREAD

**Issue by conarwelsh** [facebook/stylex#294]
**The problem**

if you `import { keyframe } from "@stylex/stylex"` the build will fail because its apparently looking for the reference of `stylex.keyframes()`

**How to reproduce**

Steps to reproduce:
1. `import { keyframe } from "@stylex/stylex"`
2. create an animation
3. try to run `next build`

**Expected behavior**

vscode in particular autocompletes to `import { stylex } from "@stylexjs/stylex"` which will fail because we cannot call that var directly, and you will receive an unrelated error about css variables. So if you simply autocomplete `props` or `create` or `keyframes` etc you can benefit from the autocomplete with an import such as `import { create, props, keyframes } from "@stylex/stylex"`.  However the build will fail with the the `keyframes` import unless it is prefixed with the base path.  `props` and `create` however work fine.

**Environment (include versions). Did this work in previous versions?**

**Comment by nedjulius** [comment]
can't reproduce it. could you share more details? specifically, what kind of error you get and what version of NextJS or stylex do you use? if you tried this in the example app, it could be that it was due to the `eslint` rule, but now that should be fixed.

**Comment by nmn** [comment]
@nedjulius Although that PR is merged, it's not in a release yet. So the ESLint error will still exist.

**Comment by nmn** [comment]
Fix released in v0.5.0.
